//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAnswer
    {
        public int SAID { get; set; }
        public int QuestionID { get; set; }
        public string Username { get; set; }
        public string Answer { get; set; }
        public bool Flagged { get; set; }
        public short Type { get; set; }
        public bool StudentAnswerActive { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
    }
}
