//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public string TokenString { get; set; }
        public string Username { get; set; }
        public int TestID { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime ExpiredTime { get; set; }
        public bool TokenActive { get; set; }
        public int TokenID { get; set; }
        public string TestComment { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual User User { get; set; }
    }
}
